### ISSUE TITLE
KeyError in wappalyzer_scan module when IIS is discovered

### ISSUE THREAD

**Issue by securestep9** [OWASP/Nettacker#338]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `debian`

**OS Version**: `Debian 5.2.9-2kali1`

**Python Version**: `3.6`

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/OWASP-Nettacker-0.0.1/lib/scan/wappalyzer/engine.py", ne 174, in analyze
    cats = apps[app_name]['cats']
**KeyError: 'IIS\\;confidence:50'**

same error happen when scanned using Python 2.7

**Comment by securestep9** [comment]
fixed by PRs #339 #343
