### ISSUE TITLE
Web UI/API broken in Python2 

### ISSUE THREAD

**Issue by securestep9** [OWASP/Nettacker#358]
Web UI/API is currently crashing with Error under Python2:

```
ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sam/Downloads/OWASP-Nettacker/api/engine.py", line 191, in index
    method_args_list=load_all_method_args(__language(), API=True))
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/OWASP-Nettacker/web/static/index.html", line 286, in top-level template code
    {{method_args_list}}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26191: ordinal not in range(128)
127.0.0.1 -  "GET / HTTP/1.1" 500 - Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

```

_________________
**OS**: `MacOS`

**OS Version**: `Catalina`

**Python Version**: `Python2.7`

**Comment by securestep9** [comment]
fixed in PR #359 - thanks @itsdivyanshjain
