### ISSUE TITLE
Python3.9: AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by tristanlatr** [OWASP/Nettacker#394]
`threading.Thread.is_alive()` should be used instead. Thanks :)

**Python Version**: `3.9`

The traceback I'm getting (several times):

```
Process http://localhost:8080->ftp_brute:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/Nettacker/core/attack.py", line 136, in start_attack
    start(
  File "/home/runner/Nettacker/lib/brute/ftp/engine.py", line 213, in start
    ports = test_ports(ports, timeout_sec, target, retries, language, num, total, time_sleep, ports_tmp_filename,
  File "/home/runner/Nettacker/lib/brute/ftp/engine.py", line 156, in test_ports
    if thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

**Comment by itsdivyanshjain** [comment]
I would like to take up this issue

**Comment by securestep9** [comment]
thanks @itsdivyanshjain - I will review this weekend. I am just just adding Python bug reference in this comment  for a background of why isAlive was deprecated in Python 3.9 https://bugs.python.org/issue37804

**Comment by itsdivyanshjain** [comment]
@securestep9 any update?

**Comment by m07med176** [comment]
is still have a problem in my script if there is another function if deprecated please tell us
