### ISSUE TITLE
Cannot delete old database record for the selected target and modules error while executing program

### ISSUE THREAD

**Issue by murtazakan** [OWASP/Nettacker#452]
**OS**: `kali`
**OS Version**: `2021.3`
**Python Version**: `3.9.7`
**PIP Version**: `21.2.4`
```
Traceback (most recent call last):
  File "/home/user/Desktop/Nettacker/nettacker.py", line 17, in <module>
   load()  # load and parse the ARGV
  File "/home/user/Desktop/Nettacker/core/parse.py", line 26, in load
    exit_code = start_scan_processes(options)
  File "/home/user/Desktop/Nettacker/core/scan_targers.py", line 80, in start_scan_processes
    remove_old_logs(
  File "/home/user/Desktop/Nettacker/database/db.py", line 130, in remove_old_logs
    session.query(HostsLog).filter(
AttributeError: 'bool' object has no attribute 'query'
```

Get this error while running the nettacker on the target site using command:
`python3 nettacker.py -i example.com --profile scan -m all --verbose`

**Comment by Ali-Razmjoo** [comment]
Hi,

Thanks for the report. Are you using SQLite (default configuration)?

Bests, Ali.

**Comment by murtazakan** [comment]
@Ali-Razmjoo Ah, yes, sorry I forgot to mention i was trying to troubleshoot the error so i changed the default database (SQLite) to MySQL

When using the default database configuration i get this error output with the same commands entered:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: scan_events

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Desktop/Nettacker/nettacker.py", line 17, in <module>
    load()  # load and parse the ARGV
  File "/home/user/Desktop/Nettacker/core/parse.py", line 26, in load
    exit_code = start_scan_processes(options)
  File "/home/user/Desktop/Nettacker/core/scan_targers.py", line 80, in start_scan_processes
    remove_old_logs(
  File "/home/user/Desktop/Nettacker/database/db.py", line 130, in remove_old_logs
    session.query(HostsLog).filter(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3136, in delete
    result = self.session.execute(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/home/user/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: scan_events
[SQL: DELETE FROM scan_events WHERE scan_events.target = ? AND scan_events.module_name = ? AND scan_events.scan_unique_id != ?]
[parameters: ('example.com', 'ssh_brute', 'uolthvbilwnuzgcuttoebmitjmiuqgnc')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

The only change i made is database name in config.py

I figured I would get similar error if I choose Postgres too.. So I didn't tried that

**Comment by Ali-Razmjoo** [comment]
In the new version of nettacker, we changed some tables, which messed up the old version. Soon, we will migrate to elastic search, and Redis and I am unsure if we can continue supporting this due to the many limitations it causes us.

@securestep9 @itsdivyanshjain @aman566 any of you can work on a script maybe to migrate the old db to the new one?

**Comment by murtazakan** [comment]
@Ali-Razmjoo What was the need for changing tables if migration wasn't initiated at all?

**Comment by Ali-Razmjoo** [comment]
I know it's an old project, but we are not even in beta, still in r&d phase and we don't think twice which is bad :D but so you know. you can keep using version 0.0.2, we just change the architecture in 0.0.3 and when it's a bit more clean code and bug-free we gonna go to next phase to add more stuff, then you might need to update...

**Comment by murtazakan** [comment]
@Ali-Razmjoo 

Ah, OK. I learned a lot from this tool, please do update it new architecture, I will be waiting for it!

I just have one more request, can you update the docker image to 0.0.2 as well? I'm not sure if it is the 0.0.2 version right now or not but I felt it was outdated cause it didn't worked on my machine. I tried creating my own docker image but was struggling and came to a dead end due to some version conflict in modules.

**Comment by Ali-Razmjoo** [comment]
There is a `Dockerfile` in the directory of version 0.0.2. So all you need to do is download the v0.0.2 from [here](https://github.com/OWASP/Nettacker/tags) and then you have two to go forward:

1- build the image yourself.
```bash
docker build . -t nettacker
docker run --rm -p 5000:5000 -v $(pwd):/usr/src/owaspnettacker:Z  -it nettacker /bin/bash
python nettacker.py
```
2- use docker-compose
```
docker-compose up -d --build && docker exec -it nettacker_nettacker_1 /bin/bash
python nettacker.py
```
* notice, I used `--build` to make sure if there is an older version of the image, it will replace it, but once you build it, you can use `docker-compose up -d && docker exec -it nettacker_nettacker_1 /bin/bash` so you don't wait for the build.
* also, docker-compose expose port 5000. You can access it by opening it in the browser.
* to check if docker container is running use, `docker ps`
* to kill the background docker container, use `docker-compose down`


And I recommend before running scans, sync with the `master` branch with `git pull`. We update this project very frequently.

**Comment by murtazakan** [comment]
@Ali-Razmjoo 

Thank you so much! The explanation on usage of docker image was very helpful.

Understanding version changes and releases is quite important, haha
