### ISSUE TITLE
Internal Server Error  

### ISSUE THREAD

**Issue by BlAd373** [OWASP/Nettacker#534]
Please describe the issue or question and share your OS and Python version.
_________________
**OS**: `x`
kali
**OS Version**: `x`
5.14.0-kali4-amd64
**Python Version**: `x`
Python 3.9.9
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

some suggestion?
ty so much

**Comment by securestep9** [comment]
@BlAd373  can you please add a screenshot where it happens/steps to reproduce?

**Comment by BlAd373** [comment]
python3 nettacker.py --start-api     

   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.0.3
  \____/   \/  \/_/    \_\_____/|_|     TRES
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/OWASP       |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  z3r0d4y.com            | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|


 * API is accessible from https://nettacker-api.z3r0d4y.com:5000/ via API Key: vvwvoeywiuqyaryftwfivzmtiirpjvjo * Serving Flask app 'api.engine' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://nettacker-api.z3r0d4y.com:5000/ (Press CTRL+C to quit)
[2022-01-07 09:17:19,268] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Pentest/Nettacker/api/engine.py", line 219, in index
    languages=languages_to_country(),
  File "/Pentest/Nettacker/api/api_core.py", line 201, in languages_to_country
    flags[language],
KeyError: 'bn'
[2022-01-07 09:17:19,268] ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Pentest/Nettacker/api/engine.py", line 219, in index
    languages=languages_to_country(),
  File "/Pentest/Nettacker/api/api_core.py", line 201, in languages_to_country
    flags[language],
KeyError: 'bn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1540, in finalize_request
    response = self.process_response(response)
  File "/home/blade/.local/lib/python3.9/site-packages/flask/app.py", line 1885, in process_response
 
![Screenshot from 2022-01-07 09-18-59](https://user-images.githubusercontent.com/22465921/148557002-cd655575-3409-4f97-808e-9d4778094bb5.png)
   response = self.ensure_sync(func)(response)
  File "/Pentest/Nettacker/api/engine.py", line 158, in access_log
    log_request = open(
PermissionError: [Errno 13] Permission denied: '/Pentest/Nettacker/.data/nettacker.log'
12
[nettacker.log](https://github.com/OWASP/Nettacker/files/7829306/nettacker.log)
7.0.0.1 - - [07/Jan/2022 09:17:19] "GET / HTTP/1.1" 500 -
