### ISSUE TITLE
MySQL not working

### ISSUE THREAD

**Issue by umardraz** [OWASP/Nettacker#555]
Hi I am trying to configure Nettacker with mysql database, but it is not working. here is my config

```
def nettacker_database_config():
    return {
        "DB": "mysql",
        "DATABASE": "nettacker",
        "USERNAME": "owasp",
        "PASSWORD": "mypasswd",
        "HOST": "localhost",
        "PORT": "3306"
    }
```

And here is the error that appear whenever submit new scan
```

Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Nettacker/core/scan_targers.py", line 114, in start_scan_processes
    options.targets = expand_targets(options, scan_unique_id)
  File "/root/Nettacker/core/targets.py", line 97, in expand_targets
    multi_processor(
  File "/root/Nettacker/core/scan_targers.py", line 72, in multi_processor
    remove_old_logs(
  File "/root/Nettacker/database/db.py", line 130, in remove_old_logs
    session.query(HostsLog).filter(
AttributeError: 'bool' object has no attribute 'query'

```
Note: the mysql database is empty there is no table in it

**Comment by securestep9** [comment]
fixed in #1001
