### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by strunz983** [OWASP/Nettacker#714]
Hello i get error message when i start nettacker.py
My OS is   6.1.0-kali9-amd64
Linux kali 6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux

My Python3 version is   Python 3.11.4 
I install requirements.txt and requirements-dev.txt

When start nettacker.py i get this

python3 nettacker.py -i testphp.vulnweb.com -s -m port_scan                                                                                                       1 ⨯

   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.3.1
  \____/   \/  \/_/    \_\_____/|_|     TRENT
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/OWASP       |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  z3r0d4y.com            | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|

[2023-07-05 12:36:47][+] Nettacker engine started ...
[2023-07-05 12:36:47][+] 84 modules loaded ...
[2023-07-05 12:36:47][+] regrouping targets based on hardware resources!
[2023-07-05 12:36:47][+] Removing old database record for selected targets and modules.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: scan_events

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/stuff/Nettacker/nettacker.py", line 17, in <module>
    load()  # load and parse the ARGV
    ^^^^^^
  File "/root/stuff/Nettacker/core/parse.py", line 26, in load
    exit_code = start_scan_processes(options)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stuff/Nettacker/core/scan_targers.py", line 114, in start_scan_processes
    options.targets = expand_targets(options, scan_unique_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/stuff/Nettacker/core/targets.py", line 60, in expand_targets
    multi_processor(
  File "/root/stuff/Nettacker/core/scan_targers.py", line 72, in multi_processor
    remove_old_logs(
  File "/root/stuff/Nettacker/database/db.py", line 134, in remove_old_logs
    ).delete(synchronize_session=False)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 3222, in delete
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: scan_events
[SQL: DELETE FROM scan_events WHERE scan_events.target = ? AND scan_events.module_name = ? AND scan_events.scan_unique_id != ?]
[parameters: ('testphp.vulnweb.com', 'subdomain_scan', 'ickpssrgtcfmovphrgnytohbbvrivres')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

Thank you :)))

Please describe the issue or question and share your OS and Python version.
_________________
**OS**: `x`

**OS Version**: `x`

**Python Version**: `x`

**Comment by securestep9** [comment]
did you have a previous version of Nettacker (0.0.1/0.0.2) in the same folder? looks like a database compatibility issue. Check your Nettacker/.data folder and rename the existing nettacker.db database to something like nettacker-old.db and try again. 

Also, please note that -s (run modules for all subdomains) makes no sense for a specific hostname (e.g. testphp.vulnweb.com).  I tried a fresh install and it worked fine :

![image](https://github.com/OWASP/Nettacker/assets/20112179/ca951926-8a63-46b7-8c47-f9ed92136221)

**Comment by strunz983** [comment]
Thank you great job :))
